#
# CHIP-8 emulator
#
# By Jaldhar H. Vyas <jaldhar@braincells.com>
# Copyright (C) 2021, Consolidated Braincells Inc.  All rights reserved.
# "Do what thou wilt" shall be the whole of the license.
#

CPPFLAGS += -DDEBUG
CXXFLAGS += -g3
VPATH = ../src:../include

include ../Makefile

STRIP=
